### PR TITLE
Add Cowboy 0.8.x Support

### PR DESCRIPTION
**Pull request by gebi**
Current master now passes all unit-test from sockjs-protocol-0.3.3.py cleanly.

(except for WebsocketHixie76 where support got removed in cowboy 0.8)
see https://github.com/extend/cowboy/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by gebi** [comment]
thx for all your hard work guys!
Without all those already existing patches it would have been a LOT more work...

**Comment by jornfranke** [comment]
Hallo,

just for my understanding: sock.js-erlang does not yet work for the newest cowboy master branch? I have somehow problems to run sock.js-erlang using the newest cowboy version. What is the latest version supported by sock.js?

Thank you!

**Comment by gebi** [comment]
@jornfranke you are right, sock-js master does not work with current cowboy, that's why i sent this pull-request, with which all sock-js unit-tests complete successfully (except those listed in my first post).

**Comment by hyperthunk** [comment]
@gebi - just for the record, this PR much appreciated. I'm glad the tests work, but there are a couple of problems here - bear in mind I've only just started looking at this, I appreciate that you submitted the patch nearly a month ago:
- this patch doesn't merge cleanly
- it contains 60 commits, so it's very difficult to QA properly

I'm guessing that what you've done is taken a bunch of changes against the development branch as well as your fixes? Is it possible to rework this patch just in terms of the changes specifically related to supporting cowboy 0.8.x, by e.g., branching from master and cherry picking the commits you need, then rebasing to get a single squashed commit? 

That would make it much easier for me to QA, then I could merge it without needing to do some much oversight. As it stands, I've got to go through all the commits and understand what's changed and why, then figure out whether they really ought to be merged into the stable master branch. And I'm not a maintainer here right now, just a helping pair of hands with a vested interest.

**Comment by hyperthunk** [comment]
> I'm guessing that what you've done is taken a bunch of changes against the development branch as well as your fixes?

Ah, it actually looks like a simple matter that your master branch is out of sync with the canonical repo. I don't know how this project was run with regards contributions, but what I typically do is this:
- no pull requests from someone else's master, unless it's rebased against mine
- all pull requests squashed down to a single commit

The latter thing isn't that important, but if your master gets out of sync with the canonical repo and then you submit a pull request, _this_ is what happens - viz, 60 odd commits that have little or nothing to do with the actual patch. Instead, what you should be doing IMHO is
- keep your master branch an **exact** copy of the upstream
- do all your changes in a branch
- when your changes are complete, rebase the upstream/master onto your master
- then rebase your master onto your branch
- then squash your branch into a single commit / patch
- **then** submit your pull request

**Comment by gebi** [comment]
What i basically did was get the "best" sock-js from all the github repos (required a bit of searching). Where "best" meant support for newest cowboy version possible.

After that i fixed up all things necessary to get support for cowboy 0.8.3 working.
I've no idea what is required to get that branch working with upstream/master, i can only try.

The pull request should merely document that there _is_ a working version of sock-js with newer cowboy as it seems there are currently 3-4 people/companies patching around on sock-js but no such work is in upstream/master.

**Comment by jornfranke** [comment]
Thanks for your help! Let me know if I can help you...

**Comment by gebi** [comment]
new clean patch series at https://github.com/sockjs/sockjs-erlang/pull/49

**Pull request closed without merging**
